
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PollingContextProvider } from "../store/contexts/PollingContext";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, session }: { children: React.ReactNode, session:any }) {
	return (
		<html lang="en">
				<body className={inter.className}>
					<ThemeProvider forcedTheme={"dark"} attribute="class" defaultTheme="system" enableSystem={true}>
						<PollingContextProvider>
							{/* <Provider session={session}> */}
							{children}
							{/* </Provider> */}
						</PollingContextProvider>
					</ThemeProvider>
				</body>
		</html>
	);
}
